version: "3.9"
services:

  ## ---API 서버--- ##
  postgresql:
    container_name: IGO-API-DB
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - TZ=Asia/Seoul
      - POSTGRES_DB=igodata
  django:
    platform: "linux/amd64"
    container_name: IGO-API-Server
    build:
    #빌드 명령어가 실행될 디렉토리 경로
      context: "./API Server/."
      dockerfile : "./Dockerfile"
    volumes:
      - "./API Server/:/home/API_Server"
    working_dir: /home/API_Server
    ports:
      - "8000:8000"
    environment:
      - SECRET_JWT_KEY=${SECRET_JWT_KEY}
    links:
      - postgresql:postgres
    command: >
      bash -c "
      chmod +x /wait-for-it.sh
      && /wait-for-it.sh postgres:5432 -t 10
      && python manage.py makemigrations Api
      && python manage.py migrate Api
      && python manage.py runserver 0.0.0.0:8000"

  ## ---Login 서버--- ##
  mongodb:
    container_name: IGO-Login-DB
    image: mongo
    restart: always
    ports:
      - "3333:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_ID}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PW}
      - TZ=Asia/Seoul
    # volumes:
      # - "./Login Server/db/data:/data/db"
    logging:
      options:
        max-size: "100m"
        max-file: "3"
  next:
    container_name: IGO-Web
    build:
      context: "./Web_Client/"
      dockerfile: "./Dockerfile"
    restart: always
    volumes:
      - "./Web_Client:/home/Web"
    # ports:
      # - "3000:3000"
    environment:
      - TZ=Asia/Seoul
      - NEXT_PUBLIC_KAKAO_MAP_REST_API_KEY=${NEXT_PUBLIC_KAKAO_MAP_REST_API_KEY}
  node:
    container_name: IGO-Login-Server
    build:
      context: "./Login Server"
      dockerfile: "./server/Dockerfile.node.dev"
    restart: always
    volumes:
    - "./Login Server/server/src:/usr/src/app/src"
    ports:
      - "23712:23712"
    environment:
      - TZ=Asia/Seoul
      - NODE_ENV=development
      - SECRET_JWT_KEY=${SECRET_JWT_KEY}
      - COOKIE_SECRET_KEY=${COOKIE_SECRET_KEY}
      - MONGO_ROOT_ID=${MONGO_ROOT_ID}
      - MONGO_ROOT_PW=${MONGO_ROOT_PW}
      - NEXT_PUBLIC_KAKAO_FIND_REST_API_KEY=${NEXT_PUBLIC_KAKAO_FIND_REST_API_KEY}
    links:
      - mongodb
      - django:backend
    depends_on:
      - mongodb
    logging:
      options:
        max-size: "100m"
        max-file: "3"

  ## ---NGINX 서버--- ##
  nginx:
    container_name: IGO-Nginx
    image: nginx:stable
    restart: always
    ports:
    # - "80:80"
    - "443:443"
    environment:
      - TZ=Asia/Seoul
    volumes:
    - "./Login Server/nginx/conf.d:/etc/nginx/conf.d"
    - "./Login Server/nginx/ssl/:/etc/nginx/ssl/"
    links:
    - node
    - django:backend
    - next
    depends_on:
    - node
    logging:
      options:
        max-size: "100m"
        max-file: "3"