version: "3.9" 
services:
  mongodb:
    image: mongo
    restart: always
    container_name: IGO-login-mongodb
    ports:
      - "3333:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - TZ=Asia/Seoul
    volumes:
      - ./data:/data/db
  nginx:
    image: nginx:stable
    restart: always
    container_name: IGO-NGINX
    ports:
    - "80:80"
    volumes:
    - ./conf.d:/etc/nginx/conf.d
    links:
    - node
    #environment:
    #- NGINX_HOST=foobar.com
  node:
    container_name: nodejs
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.node.dev
    volumes:
    - ./src:/usr/src/app/src
    - ./package.json:/usr/src/app/package.json
    - ./package-lock.json:/usr/src/app/package-lock.json
    ports:
      - "23712:23712"
    links:
      - mongodb