FROM node:lts-alpine3.15

# alpine linux python3설치
RUN apk --no-cache add --virtual builds-deps build-base python3

# 앱 디렉터리 생성
WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

# 앱 소스 추가
COPY . .

EXPOSE 23712

CMD [ "npm", "run","dev" ]