version: "3.9"
services:
  postgres:
    container_name: IGO-API-postgresdb
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - TZ=Asia/Seoul
      - POSTGRES_DB=igodata
  backend:
    platform: "linux/amd64"
    container_name: IGO-API-backend
    build:
    #빌드 명령어가 실행될 디렉토리 경로
      context: .
      dockerfile : ./Dockerfile
    volumes:
      - ./:/home/API_Server
    working_dir: /home/API_Server
    links:
      - postgres
    command: >
      bash -c "
      chmod +x /wait-for-it.sh
      && /wait-for-it.sh postgres:5432 -t 10
      && python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver"
    ports:
      - "8000:8000"
      