version: "3.9"
services:
  postgresdb:
    container_name: IGO-API-postgresdb
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - TZ=Asia/Seoul